// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.21.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'simple.freezed.dart';

String greet({required String name, dynamic hint}) =>
    RustLib.instance.api.greet(name: name, hint: hint);

Future<EnumTest> foo({dynamic hint}) => RustLib.instance.api.foo(hint: hint);

@freezed
sealed class EnumTest with _$EnumTest {
  const factory EnumTest.a() = EnumTest_A;
  const factory EnumTest.b() = EnumTest_B;
  const factory EnumTest.c(
    String field0,
  ) = EnumTest_C;
}
